# Screen
SCREEN_X = 300
SCREEN_Y = 50
SCREEN_WIDTH = 1300
SCREEN_HEIGHT = 960
SCREEN_HALF_WIDTH = SCREEN_WIDTH // 2
SCREEN_HALF_HEIGHT = SCREEN_HEIGHT // 2
SCREEN_TOP_MARGIN = 8
SCREEN_BOTTOM_MARGIN = 8
SCREEN_LEFT_MARGIN = 80
SCREEN_RIGHT_MARGIN = 80
